-- params : ...
-- function num : 0 , upvalues : _ENV
require("GuildBoss_Red_1ByName")
require("GuildBoss_Red_2ByName")
require("GuildBoss_Red_3ByName")
require("GuildBoss_Red_4ByName")
require("GuildBoss_Red_5ByName")
require("GuildBoss_SkillByName")
require("GuildBoss_Yellow_1ByName")
require("GuildBoss_Yellow_2ByName")
require("GuildBoss_Yellow_3ByName")
require("GuildBoss_Yellow_4ByName")
require("GuildBoss_Yellow_5ByName")
require("GuildBoss_Blue_1ByName")
require("GuildBoss_Blue_2ByName")
require("GuildBoss_Blue_3ByName")
require("GuildBoss_Blue_4ByName")
require("GuildBoss_Blue_5ByName")
require("GuildBoss_Green_1ByName")
require("GuildBoss_Green_2ByName")
require("GuildBoss_Green_3ByName")
require("GuildBoss_Green_4ByName")
GetGuildBoss_SkillTreeUis = function(ui, ...)
  -- function num : 0_0 , upvalues : _ENV
  local uis = {}
  uis.RedLine_1 = GetGuildBoss_Red_1Uis(ui:GetChild("RedLine_1"))
  uis.RedLine_2 = GetGuildBoss_Red_2Uis(ui:GetChild("RedLine_2"))
  uis.RedLine_3 = GetGuildBoss_Red_3Uis(ui:GetChild("RedLine_3"))
  uis.RedLine_4 = GetGuildBoss_Red_4Uis(ui:GetChild("RedLine_4"))
  uis.RedLine_5 = GetGuildBoss_Red_5Uis(ui:GetChild("RedLine_5"))
  uis.RedSkill_1 = GetGuildBoss_SkillUis(ui:GetChild("RedSkill_1"))
  uis.RedSkill_2 = GetGuildBoss_SkillUis(ui:GetChild("RedSkill_2"))
  uis.RedSkill_3 = GetGuildBoss_SkillUis(ui:GetChild("RedSkill_3"))
  uis.RedSkill_4 = GetGuildBoss_SkillUis(ui:GetChild("RedSkill_4"))
  uis.RedSkill_5 = GetGuildBoss_SkillUis(ui:GetChild("RedSkill_5"))
  uis.YellowLine_1 = GetGuildBoss_Yellow_1Uis(ui:GetChild("YellowLine_1"))
  uis.YellowLine_2 = GetGuildBoss_Yellow_2Uis(ui:GetChild("YellowLine_2"))
  uis.YellowLine_3 = GetGuildBoss_Yellow_3Uis(ui:GetChild("YellowLine_3"))
  uis.YellowLine_4 = GetGuildBoss_Yellow_4Uis(ui:GetChild("YellowLine_4"))
  uis.YellowLine_5 = GetGuildBoss_Yellow_5Uis(ui:GetChild("YellowLine_5"))
  uis.YellowSkill_1 = GetGuildBoss_SkillUis(ui:GetChild("YellowSkill_1"))
  uis.YellowSkill_2 = GetGuildBoss_SkillUis(ui:GetChild("YellowSkill_2"))
  uis.YellowSkill_3 = GetGuildBoss_SkillUis(ui:GetChild("YellowSkill_3"))
  uis.YellowSkill_4 = GetGuildBoss_SkillUis(ui:GetChild("YellowSkill_4"))
  uis.YellowSkill_5 = GetGuildBoss_SkillUis(ui:GetChild("YellowSkill_5"))
  uis.BlueLine_1 = GetGuildBoss_Blue_1Uis(ui:GetChild("BlueLine_1"))
  uis.BlueLine_2 = GetGuildBoss_Blue_2Uis(ui:GetChild("BlueLine_2"))
  uis.BlueLine_3 = GetGuildBoss_Blue_3Uis(ui:GetChild("BlueLine_3"))
  uis.BlueLine_4 = GetGuildBoss_Blue_4Uis(ui:GetChild("BlueLine_4"))
  uis.BlueLine_5 = GetGuildBoss_Blue_5Uis(ui:GetChild("BlueLine_5"))
  uis.BlueSkill_1 = GetGuildBoss_SkillUis(ui:GetChild("BlueSkill_1"))
  uis.BlueSkill_2 = GetGuildBoss_SkillUis(ui:GetChild("BlueSkill_2"))
  uis.BlueSkill_3 = GetGuildBoss_SkillUis(ui:GetChild("BlueSkill_3"))
  uis.BlueSkill_4 = GetGuildBoss_SkillUis(ui:GetChild("BlueSkill_4"))
  uis.BlueSkill_5 = GetGuildBoss_SkillUis(ui:GetChild("BlueSkill_5"))
  uis.GreenLine_2 = GetGuildBoss_Green_1Uis(ui:GetChild("GreenLine_2"))
  uis.GreenLine_3 = GetGuildBoss_Green_2Uis(ui:GetChild("GreenLine_3"))
  uis.GreenLine_4 = GetGuildBoss_Green_3Uis(ui:GetChild("GreenLine_4"))
  uis.GreenLine_5 = GetGuildBoss_Green_4Uis(ui:GetChild("GreenLine_5"))
  uis.GreenSkill_1 = GetGuildBoss_SkillUis(ui:GetChild("GreenSkill_1"))
  uis.GreenSkill_2 = GetGuildBoss_SkillUis(ui:GetChild("GreenSkill_2"))
  uis.GreenSkill_3 = GetGuildBoss_SkillUis(ui:GetChild("GreenSkill_3"))
  uis.GreenSkill_4 = GetGuildBoss_SkillUis(ui:GetChild("GreenSkill_4"))
  uis.GreenSkill_5 = GetGuildBoss_SkillUis(ui:GetChild("GreenSkill_5"))
  uis.root = ui
  return uis
end


